KAADO-21: Implement add card type page
tsoibet/kaado pull request #13
Opened 2023-10-10 10:04 UTC by nasudon

- Implement add card type page

2023-10-13 07:00 UTC, tsoibet requested changes

2023-10-13 07:00 UTC, tsoibet commented on src/app/type/new/form.tsx
> +                    <br />
New line is not needed here. Sorry for the misleading design picture.

2023-10-14 14:45 UTC, nasudon commented on src/app/type/new/form.tsx
> +                    <br />
Updated: https://github.com/tsoibet/kaado/pull/13/commits/f40524599e0e2b9300e74c6fbf4300895458e5ff

2023-10-14 14:48 UTC, tsoibet approved these changes
LGTM

2023-10-14 15:18 UTC, merged